/**
 * Figma SDS tokens — use CSS variables only (no raw hex in app/Tailwind config).
 * Literal values are defined in theme.css (:root).
 * Regenerate: npm run tokens:build (source: scripts/figma-variable-defs.json)
 */

export const cssVar = (name) => `var(${name})`;

/** Flat map: Tailwind key → var(--...) */
export const tokens = {
  colors: {
  "sds-color-text-default-default": "var(--sds-color-text-default-default)",
  "sds-color-border-default-default": "var(--sds-color-border-default-default)",
  "sds-color-background-warning-tertiary": "var(--sds-color-background-warning-tertiary)",
  "sds-color-border-warning-tertiary": "var(--sds-color-border-warning-tertiary)",
  "sds-color-background-default-default": "var(--sds-color-background-default-default)",
  "sds-color-background-default-secondary": "var(--sds-color-background-default-secondary)",
  "sds-color-icon-warning-on-warning-secondary": "var(--sds-color-icon-warning-on-warning-secondary)",
  "sds-color-text-warning-on-warning-secondary": "var(--sds-color-text-warning-on-warning-secondary)",
  "sds-color-border-warning-default": "var(--sds-color-border-warning-default)",
  "sds-color-text-warning-on-warning-tertiary": "var(--sds-color-text-warning-on-warning-tertiary)",
  "sds-color-background-warning-secondary": "var(--sds-color-background-warning-secondary)",
  "sds-color-black-100": "var(--sds-color-black-100)",
  "sds-color-black-200": "var(--sds-color-black-200)",
  "sds-color-border-utilities-swatch": "var(--sds-color-border-utilities-swatch)",
  "sds-color-background-default-default-hover": "var(--sds-color-background-default-default-hover)",
  "sds-color-background-default-secondary-hover": "var(--sds-color-background-default-secondary-hover)",
  "sds-color-background-default-tertiary": "var(--sds-color-background-default-tertiary)",
  "sds-color-background-default-tertiary-hover": "var(--sds-color-background-default-tertiary-hover)",
  "sds-color-background-disabled-default": "var(--sds-color-background-disabled-default)",
  "sds-color-background-brand-default": "var(--sds-color-background-brand-default)",
  "sds-color-background-brand-hover": "var(--sds-color-background-brand-hover)",
  "sds-color-background-brand-secondary": "var(--sds-color-background-brand-secondary)",
  "sds-color-background-brand-secondary-hover": "var(--sds-color-background-brand-secondary-hover)",
  "sds-color-background-neutral-default": "var(--sds-color-background-neutral-default)",
  "sds-color-background-neutral-hover": "var(--sds-color-background-neutral-hover)",
  "sds-color-background-neutral-secondary": "var(--sds-color-background-neutral-secondary)",
  "sds-color-background-neutral-secondary-hover": "var(--sds-color-background-neutral-secondary-hover)",
  "sds-color-background-neutral-tertiary": "var(--sds-color-background-neutral-tertiary)",
  "sds-color-background-neutral-tertiary-hover": "var(--sds-color-background-neutral-tertiary-hover)",
  "sds-color-background-positive-default": "var(--sds-color-background-positive-default)",
  "sds-color-background-positive-hover": "var(--sds-color-background-positive-hover)",
  "sds-color-background-positive-secondary": "var(--sds-color-background-positive-secondary)",
  "sds-color-background-positive-secondary-hover": "var(--sds-color-background-positive-secondary-hover)",
  "sds-color-background-positive-tertiary": "var(--sds-color-background-positive-tertiary)",
  "sds-color-background-positive-tertiary-hover": "var(--sds-color-background-positive-tertiary-hover)",
  "sds-color-background-warning-default": "var(--sds-color-background-warning-default)",
  "sds-color-background-warning-hover": "var(--sds-color-background-warning-hover)",
  "sds-color-background-warning-tertiary-hover": "var(--sds-color-background-warning-tertiary-hover)",
  "sds-color-background-danger-default": "var(--sds-color-background-danger-default)",
  "sds-color-background-danger-hover": "var(--sds-color-background-danger-hover)",
  "sds-color-background-danger-secondary": "var(--sds-color-background-danger-secondary)",
  "sds-color-background-danger-secondary-hover": "var(--sds-color-background-danger-secondary-hover)",
  "sds-color-background-danger-tertiary": "var(--sds-color-background-danger-tertiary)",
  "sds-color-background-danger-tertiary-hover": "var(--sds-color-background-danger-tertiary-hover)",
  "sds-color-text-neutral-on-neutral-tertiary": "var(--sds-color-text-neutral-on-neutral-tertiary)",
  "sds-color-border-neutral-tertiary": "var(--sds-color-border-neutral-tertiary)",
  "sds-color-text-neutral-on-neutral-secondary": "var(--sds-color-text-neutral-on-neutral-secondary)",
  "sds-color-background-utilities-scrim": "var(--sds-color-background-utilities-scrim)",
  "sds-color-background-utilities-blanket": "var(--sds-color-background-utilities-blanket)",
  "sds-color-background-utilities-overlay": "var(--sds-color-background-utilities-overlay)",
  "sds-color-border-default-secondary": "var(--sds-color-border-default-secondary)",
  "sds-color-border-default-tertiary": "var(--sds-color-border-default-tertiary)",
  "sds-color-border-disabled-default": "var(--sds-color-border-disabled-default)",
  "sds-color-border-brand-default": "var(--sds-color-border-brand-default)",
  "sds-color-border-brand-secondary": "var(--sds-color-border-brand-secondary)",
  "sds-color-border-brand-tertiary": "var(--sds-color-border-brand-tertiary)",
  "sds-color-border-neutral-default": "var(--sds-color-border-neutral-default)",
  "sds-color-border-neutral-secondary": "var(--sds-color-border-neutral-secondary)",
  "sds-color-border-positive-default": "var(--sds-color-border-positive-default)",
  "sds-color-border-positive-secondary": "var(--sds-color-border-positive-secondary)",
  "sds-color-border-positive-tertiary": "var(--sds-color-border-positive-tertiary)",
  "sds-color-border-warning-secondary": "var(--sds-color-border-warning-secondary)",
  "sds-color-border-danger-default": "var(--sds-color-border-danger-default)",
  "sds-color-border-danger-secondary": "var(--sds-color-border-danger-secondary)",
  "sds-color-border-danger-tertiary": "var(--sds-color-border-danger-tertiary)",
  "sds-color-text-default-secondary": "var(--sds-color-text-default-secondary)",
  "sds-color-text-default-tertiary": "var(--sds-color-text-default-tertiary)",
  "sds-color-text-disabled-default": "var(--sds-color-text-disabled-default)",
  "sds-color-text-disabled-on-disabled": "var(--sds-color-text-disabled-on-disabled)",
  "sds-color-text-brand-default": "var(--sds-color-text-brand-default)",
  "sds-color-text-brand-secondary": "var(--sds-color-text-brand-secondary)",
  "sds-color-text-brand-tertiary": "var(--sds-color-text-brand-tertiary)",
  "sds-color-text-brand-on-brand": "var(--sds-color-text-brand-on-brand)",
  "sds-color-text-brand-on-brand-secondary": "var(--sds-color-text-brand-on-brand-secondary)",
  "sds-color-text-brand-on-brand-tertiary": "var(--sds-color-text-brand-on-brand-tertiary)",
  "sds-color-text-neutral-default": "var(--sds-color-text-neutral-default)",
  "sds-color-text-neutral-secondary": "var(--sds-color-text-neutral-secondary)",
  "sds-color-text-neutral-tertiary": "var(--sds-color-text-neutral-tertiary)",
  "sds-color-text-neutral-on-neutral": "var(--sds-color-text-neutral-on-neutral)",
  "sds-color-text-danger-default": "var(--sds-color-text-danger-default)",
  "sds-color-text-danger-secondary": "var(--sds-color-text-danger-secondary)",
  "sds-color-text-danger-tertiary": "var(--sds-color-text-danger-tertiary)",
  "sds-color-text-danger-on-danger": "var(--sds-color-text-danger-on-danger)",
  "sds-color-text-danger-on-danger-secondary": "var(--sds-color-text-danger-on-danger-secondary)",
  "sds-color-text-danger-on-danger-tertiary": "var(--sds-color-text-danger-on-danger-tertiary)",
  "sds-color-text-warning-default": "var(--sds-color-text-warning-default)",
  "sds-color-text-warning-secondary": "var(--sds-color-text-warning-secondary)",
  "sds-color-text-warning-tertiary": "var(--sds-color-text-warning-tertiary)",
  "sds-color-text-warning-on-warning": "var(--sds-color-text-warning-on-warning)",
  "sds-color-text-positive-default": "var(--sds-color-text-positive-default)",
  "sds-color-text-positive-secondary": "var(--sds-color-text-positive-secondary)",
  "sds-color-text-positive-tertiary": "var(--sds-color-text-positive-tertiary)",
  "sds-color-text-positive-on-positive": "var(--sds-color-text-positive-on-positive)",
  "sds-color-text-positive-on-positive-secondary": "var(--sds-color-text-positive-on-positive-secondary)",
  "sds-color-text-positive-on-positive-tertiary": "var(--sds-color-text-positive-on-positive-tertiary)",
  "sds-color-icon-default-default": "var(--sds-color-icon-default-default)",
  "sds-color-icon-default-secondary": "var(--sds-color-icon-default-secondary)",
  "sds-color-icon-default-tertiary": "var(--sds-color-icon-default-tertiary)",
  "sds-color-icon-disabled-default": "var(--sds-color-icon-disabled-default)",
  "sds-color-icon-brand-default": "var(--sds-color-icon-brand-default)",
  "sds-color-icon-brand-secondary": "var(--sds-color-icon-brand-secondary)",
  "sds-color-icon-brand-on-brand-tertiary": "var(--sds-color-icon-brand-on-brand-tertiary)",
  "sds-color-icon-brand-on-brand": "var(--sds-color-icon-brand-on-brand)",
  "sds-color-icon-brand-on-brand-secondary": "var(--sds-color-icon-brand-on-brand-secondary)",
  "sds-color-icon-neutral-default": "var(--sds-color-icon-neutral-default)",
  "sds-color-icon-neutral-secondary": "var(--sds-color-icon-neutral-secondary)",
  "sds-color-icon-neutral-tertiary": "var(--sds-color-icon-neutral-tertiary)",
  "sds-color-icon-neutral-on-neutral": "var(--sds-color-icon-neutral-on-neutral)",
  "sds-color-icon-neutral-on-neutral-secondary": "var(--sds-color-icon-neutral-on-neutral-secondary)",
  "sds-color-icon-neutral-on-neutral-tertiary": "var(--sds-color-icon-neutral-on-neutral-tertiary)",
  "sds-color-icon-positive-default": "var(--sds-color-icon-positive-default)",
  "sds-color-icon-positive-secondary": "var(--sds-color-icon-positive-secondary)",
  "sds-color-icon-positive-tertiary": "var(--sds-color-icon-positive-tertiary)",
  "sds-color-icon-positive-on-positive": "var(--sds-color-icon-positive-on-positive)",
  "sds-color-icon-positive-on-positive-secondary": "var(--sds-color-icon-positive-on-positive-secondary)",
  "sds-color-icon-positive-on-positive-tertiary": "var(--sds-color-icon-positive-on-positive-tertiary)",
  "sds-color-icon-warning-default": "var(--sds-color-icon-warning-default)",
  "sds-color-icon-warning-secondary": "var(--sds-color-icon-warning-secondary)",
  "sds-color-icon-warning-tertiary": "var(--sds-color-icon-warning-tertiary)",
  "sds-color-icon-warning-on-warning": "var(--sds-color-icon-warning-on-warning)",
  "sds-color-icon-warning-on-warning-tertiary": "var(--sds-color-icon-warning-on-warning-tertiary)",
  "sds-color-icon-danger-default": "var(--sds-color-icon-danger-default)",
  "sds-color-icon-danger-secondary": "var(--sds-color-icon-danger-secondary)",
  "sds-color-icon-danger-tertiary": "var(--sds-color-icon-danger-tertiary)",
  "sds-color-icon-danger-on-danger": "var(--sds-color-icon-danger-on-danger)",
  "sds-color-icon-danger-on-danger-secondary": "var(--sds-color-icon-danger-on-danger-secondary)",
  "sds-color-icon-danger-on-danger-tertiary": "var(--sds-color-icon-danger-on-danger-tertiary)",
  "sds-color-background-utilities-measurement": "var(--sds-color-background-utilities-measurement)"
},
  fontFamily: {
  "sds-typography-title-hero-font-family": "var(--sds-typography-title-hero-font-family)",
  "sds-typography-title-page-font-family": "var(--sds-typography-title-page-font-family)",
  "sds-typography-subtitle-font-family": "var(--sds-typography-subtitle-font-family)",
  "sds-typography-heading-font-family": "var(--sds-typography-heading-font-family)",
  "sds-typography-subheading-font-family": "var(--sds-typography-subheading-font-family)",
  "sds-typography-body-font-family": "var(--sds-typography-body-font-family)",
  "sds-typography-code-font-family": "var(--sds-typography-code-font-family)",
  "sds-typography-family-mono": "var(--sds-typography-family-mono)"
},
  fontSize: {
  "sds-typography-title-hero-size": "var(--sds-typography-title-hero-size)",
  "sds-typography-title-page-size-base": "var(--sds-typography-title-page-size-base)",
  "sds-typography-subtitle-size-base": "var(--sds-typography-subtitle-size-base)",
  "sds-typography-heading-size-base": "var(--sds-typography-heading-size-base)",
  "sds-typography-subheading-size-medium": "var(--sds-typography-subheading-size-medium)",
  "sds-typography-body-size-medium": "var(--sds-typography-body-size-medium)",
  "sds-typography-body-size-small": "var(--sds-typography-body-size-small)",
  "sds-typography-code-size-base": "var(--sds-typography-code-size-base)",
  "sds-typography-scale-03": "var(--sds-typography-scale-03)"
},
  fontWeight: {
  "sds-typography-title-hero-font-weight": "var(--sds-typography-title-hero-font-weight)",
  "sds-typography-title-page-font-weight": "var(--sds-typography-title-page-font-weight)",
  "sds-typography-subtitle-font-weight": "var(--sds-typography-subtitle-font-weight)",
  "sds-typography-heading-font-weight": "var(--sds-typography-heading-font-weight)",
  "sds-typography-subheading-font-weight": "var(--sds-typography-subheading-font-weight)",
  "sds-typography-body-font-weight-regular": "var(--sds-typography-body-font-weight-regular)",
  "sds-typography-body-font-weight-strong": "var(--sds-typography-body-font-weight-strong)",
  "sds-typography-code-font-weight": "var(--sds-typography-code-font-weight)",
  "sds-typography-weight-regular": "var(--sds-typography-weight-regular)",
  "sds-typography-weight-bold": "var(--sds-typography-weight-bold)"
},
  spacing: {
  "sds-size-space-300": "var(--sds-size-space-300)",
  "sds-size-space-400": "var(--sds-size-space-400)",
  "sds-size-space-800": "var(--sds-size-space-800)",
  "sds-size-space-1600": "var(--sds-size-space-1600)",
  "sds-size-padding-xl": "var(--sds-size-padding-xl)",
  "sds-size-space-200": "var(--sds-size-space-200)",
  "sds-size-icon-small": "var(--sds-size-icon-small)",
  "sds-size-depth-0": "var(--sds-size-depth-0)",
  "sds-size-depth-100": "var(--sds-size-depth-100)",
  "sds-size-depth-negative-025": "var(--sds-size-depth-negative-025)",
  "sds-size-depth-025": "var(--sds-size-depth-025)",
  "sds-size-space-100": "var(--sds-size-space-100)",
  "sds-size-space-600": "var(--sds-size-space-600)",
  "sds-size-space-negative-100": "var(--sds-size-space-negative-100)",
  "sds-size-space-negative-200": "var(--sds-size-space-negative-200)",
  "sds-size-space-negative-300": "var(--sds-size-space-negative-300)",
  "sds-size-space-negative-400": "var(--sds-size-space-negative-400)",
  "sds-size-space-negative-600": "var(--sds-size-space-negative-600)",
  "sds-size-space-2400": "var(--sds-size-space-2400)",
  "sds-size-space-4000": "var(--sds-size-space-4000)"
},
  borderRadius: {
  "sds-size-radius-200": "var(--sds-size-radius-200)",
  "sds-size-radius-xl": "var(--sds-size-radius-xl)",
  "sds-size-radius-full": "var(--sds-size-radius-full)",
  "sds-size-radius-400": "var(--sds-size-radius-400)",
  "sds-size-radius-100": "var(--sds-size-radius-100)"
},
  borderWidth: {
  "sds-size-stroke-border": "var(--sds-size-stroke-border)"
},
};

/** Typography presets referencing SDS variables */
export const typography = {
  titleHero: {
    fontFamily: "var(--sds-typography-title-hero-font-family)",
    fontSize: "var(--sds-typography-title-hero-size)",
    fontWeight: "var(--sds-typography-title-hero-font-weight)",
    lineHeight: "1.2",
    letterSpacing: "-0.03em",
  },
  titlePage: {
    fontFamily: "var(--sds-typography-title-page-font-family)",
    fontSize: "var(--sds-typography-title-page-size-base)",
    fontWeight: "var(--sds-typography-title-page-font-weight)",
    lineHeight: "1.2",
    letterSpacing: "-0.02em",
  },
  subtitle: {
    fontFamily: "var(--sds-typography-subtitle-font-family)",
    fontSize: "var(--sds-typography-subtitle-size-base)",
    fontWeight: "var(--sds-typography-subtitle-font-weight)",
    lineHeight: "1.2",
  },
  heading: {
    fontFamily: "var(--sds-typography-heading-font-family)",
    fontSize: "var(--sds-typography-heading-size-base)",
    fontWeight: "var(--sds-typography-heading-font-weight)",
    lineHeight: "1.2",
    letterSpacing: "-0.02em",
  },
  subheading: {
    fontFamily: "var(--sds-typography-subheading-font-family)",
    fontSize: "var(--sds-typography-subheading-size-medium)",
    fontWeight: "var(--sds-typography-subheading-font-weight)",
    lineHeight: "1.2",
  },
  body: {
    fontFamily: "var(--sds-typography-body-font-family)",
    fontSize: "var(--sds-typography-body-size-medium)",
    fontWeight: "var(--sds-typography-body-font-weight-regular)",
    lineHeight: "1.4",
  },
  bodyStrong: {
    fontFamily: "var(--sds-typography-body-font-family)",
    fontSize: "var(--sds-typography-body-size-medium)",
    fontWeight: "var(--sds-typography-body-font-weight-strong)",
    lineHeight: "1.4",
  },
  bodySmall: {
    fontFamily: "var(--sds-typography-body-font-family)",
    fontSize: "var(--sds-typography-body-size-small)",
    fontWeight: "var(--sds-typography-body-font-weight-regular)",
    lineHeight: "1.4",
  },
  bodyCode: {
    fontFamily: "var(--sds-typography-code-font-family)",
    fontSize: "var(--sds-typography-code-size-base)",
    fontWeight: "var(--sds-typography-code-font-weight)",
    lineHeight: "1.3",
  },
};
